### ISSUE TITLE
kardinaliteit plaatselijk phenomeen klopt niet

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/SPR#10]
## Type issue
issue ontdekt tijdens implementatie

## Waar
pagina 43 paragraaf 9.1.8 catalogus 0.99

## Samenvatting
kardinaliteit plaatselijk phenomeen klopt niet

## Beschrijving
In het diagram in de catalogus staat bij WANDPROFIEL (SOILPROFILE) een element PLAATSELIJK_PHENOMEEN met een cardinaliteit van 1..*. In de JAVA code gegenereerd via XSD is het ook een 1..* cardinaliteit (eigenlijk 0..n). Echter in de catalogus echter staat als cardinaliteit 1.

## Oplossingsrichting
werkafspraak publiceren die aangeeft dat de cardinaliteit 1..* moet zijn zoals in het UML diagram

**Comment by BregjeBrugman** [comment]
Opgelost in catalogus v1.99 met kardinaliteit 1..*
