### ISSUE TITLE
In regels bepaalde gronden ontbreekt moerigMateriaal

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#11]
## Type issue
Gevonden tijdens implementatie mapping procedure BIS profielkuilen naar BRO SFR

## Waar
Diverse paragrafen (bv paragraaf 9.5.7 pagina 63)

## Samenvatting
In de opsomming veen, kleiigVeen, venigeKlei, venigZand of zandigVeen ontbreekt moerigMateriaal.

## Beschrijving
De regel zegt 

Het gegeven is aanwezig wanneer de waarde van het attribuut beschrijfkwaliteit van de entiteit Wandprofiel gelijk is aan hoog en de waarde van het attribuut bodemkundige grondsoort ongelijk is aan veen, kleiigVeen, venigeKlei, venigZand of zandigVeen. In andere gevallen mag het gegeven ontbreken.

In deze opsomming ontbreekt 'moerigMateriaal'. Deze is ooit toegevoegd bij BHR-P omdat toen in sommige oude boringen te weinign informatie beschikbaar was om een grondsoort te definieren. Overigens ontbreekt dit ook in de catalogus van BHR-P.

## Oplossingsrichting
Op alle plekken waar de opsomming een rol speelt in een regel moerigMateriaal toevoegen en dit dus ook in de catalogus van BHR-P.

**Comment by BregjeBrugman** [comment]
Dit issue is opgelost in de werkafspraak tranche 3 (nr. 4)
