### ISSUE TITLE
Codelijst 1. ActueelProces (blz. 100)

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#12]
## Type issue
Gevonden tijdens implementatie

## Waar
Codelijst 1. ActueelProces (blz. 100)

## Samenvatting
Omschrijving bij de waarde “piping”  Water stroomt onder een dijk of ander grondlichaam door om buitendijks binnendijks aan het oppervlak te komen.

## Beschrijving
Omschrijving bij de waarde “piping”  Water stroomt onder een dijk of ander grondlichaam door om buitendijks binnendijks aan het oppervlak te komen.

## Oplossingsrichting
Aanpassen in catalogus

**Comment by BregjeBrugman** [comment]
buitendijks veranderd in binnendijks in catalogus versie 1.99
