### ISSUE TITLE
waardelijst VormAggregaat - waarde granulair ontbreekt

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#13]
## Type issue
Gevonden tijdens implementatie mapping BIS -> BRO

## Waar
Codelijst 4. Aggregaatvorm (blz. 101)

## Samenvatting
De waarde “granulair” ontbreekt in de codelijst Omschrijving als bij blok maar de buitenkant verschilt met blok omdat de vorm (afge)rond is waardoor ribben (kubusvorm) ontbreken.

## Beschrijving
De waarde “granulair” ontbreekt in de codelijst Omschrijving als bij blok maar de buitenkant verschilt met blok omdat de vorm (afge)rond is waardoor ribben (kubusvorm) ontbreken.

## Oplossingsrichting
Voorstel nieuwe Omschrijving:

| Waarde	| IMBRO	| IMBRO/A |Omschrijving |
| ----- | ----- | ----- | ----- |
| blok		| V	| V	| Het gemiddelde aggregaat is in alle richtingen 
ongeveer even lang en heeft een kubusvorm. |
| granulair |	V	| V	|Het gemiddelde aggregaat is in alle richtingen ongeveer even lang en heeft een afgeronde vorm. |

**Comment by BregjeBrugman** [comment]
geen extra waarde nodig. Voor de vorm granulair is de mapping: vorm = blok, hoekigheid = afgerond

**Comment by OnnoRoosenschoon** [comment]
Wij zijn het niet eens met deze beslissing. Granulair is granulair. Graag heropenen

**Comment by fterpstra** [comment]
Volgens fokke is Granulair toch echt anders. WENR gaat issue indienen bij servicedesk en daarbij aangeven hoeveel aanleveringen geblokkeerd worden. Mappen naar bestaande codes levert bodemkundig niet wenselijke informatie op.
