### ISSUE TITLE
waardelijst BijzonderMateriaal - waarden ontbreken

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#14]
## Type issue
Gevonden tijdens implementatie mapping BIS -> BRO

## Waar
Codelijst 12. BijzonderMateriaal (blz. 112)

## Samenvatting
De waarden “moeraskalk”, “zachte kalksteen” (eventueel “zachte mergel”) en “vuurstenen” ontbreken in de codelijst.

## Beschrijving
De waarden “moeraskalk”, “zachte kalksteen” (eventueel “zachte mergel”) en “vuurstenen” ontbreken in de codelijst.

## Oplossingsrichting
Waarden toevoegen aan codelijst
[Geef een suggestie voor een oplossing, in de vorm van een tekstvoorstel of een oplossingsrichting.]

**Comment by BregjeBrugman** [comment]
kalkgyttja is toegevoegd voor moeraskalk. Dit issue is opgenomen in de werkafspraak tranche 3 (nr. 8)
zachte kalksteen (mergel) wordt als grond beschreven (niet als bijz. materiaal)
vuursteeneluvium wordt beschreven als grond (dat zal een variant van grind zijn, en niet als bijz. materiaal)
