### ISSUE TITLE
waardelijst Bodemgebruik mapping naar akkerBollen en akkerGewas

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#15]
## Type issue
Gevonden tijdens implementatie mapping BIS -> BRO

## Waar
Codelijst 13. Bodemgebruik (blz. 113)

## Samenvatting
Zowel de naam van het attribuut (voorheen landgebruik) als de codelijst zijn veranderd ten opzichte van het registratie-object BHR-p. Vanwege afstemming met registratie-object geotechnische boorbeschrijving zijn deze veranderingen doorgevoerd. Dit komt de uniformiteit en standaardisering met BHR-p niet ten goede maar geeft voor het registratie-object op zich geen problemen.

## Beschrijving
Zowel de naam van het attribuut (voorheen landgebruik) als de codelijst zijn veranderd ten opzichte van het registratie-object BHR-p. Vanwege afstemming met registratie-object geotechnische boorbeschrijving zijn deze veranderingen doorgevoerd. Dit komt de uniformiteit en standaardisering met BHR-p niet ten goede maar geeft voor het registratie-object op zich geen problemen. Het volgende echter wel:

In de nieuwe codelijst zit nu ook een extra waarde “akkerBollen”. Op zich is het geen probleem om meer teelten te onderscheiden. Echter bij de mapping van IMBRO/A geeft dit een ongewenst effect. Bodemkundigen hebben tot nu toe de bloembollenteelt ondergebracht bij de overige akkerbouwgewassen dat daarmee vertaald wordt naar de waarde “akkerGewas”. Bij de toelichting van “akkerGewas” staat echter: “Terrein in landelijk gebied in gebruik voor akkerbouw of vollegrondstuinbouw, maar niet voor aardappelen, bieten, bloembollen, granen of mais.”

## Oplossingsrichting
Overleg en dan besluit nemen.

**Comment by BregjeBrugman** [comment]
Dit is geen issue voor de standaard, maar voor de mapping.
