### ISSUE TITLE
Codelijst 16.BodemkundigeGrondsoort (blz. 124)

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#16]
## Type issue
Gevonden tijdens implementatie mapping BIS -> BRO

## Waar
Codelijst 16.BodemkundigeGrondsoort (blz. 124)

## Samenvatting
Waarde “moerigMateriaal” ontbreekt in codelijst (alleen geldig voor kwaliteitsregime IMBRO/A).
(Ontbreekt ook in de catalogus van BHR-p omdat deze waarde later is toegevoegd; zit wel in het BRO-model BHR-p).

## Beschrijving
Waarde “moerigMateriaal” ontbreekt in codelijst (alleen geldig voor kwaliteitsregime IMBRO/A).
(Ontbreekt ook in de catalogus van BHR-p omdat deze waarde later is toegevoegd; zit wel in het BRO-model BHR-p).

##Duplicates
https://github.com/BROprogramma/SFR/issues/37
https://github.com/BROprogramma/SFR/issues/11

## Oplossingsrichting
Opnemen in beide catalogi !!!!!!!!!!!!!!!!!!

**Comment by BregjeBrugman** [comment]
ik sluit deze omdat dit issue dubbel is geregistreerd. #37 blijft open staan tot het is verwerkt
