### ISSUE TITLE
waardelijst Kleur in omschrijving dubbele kleuren

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#17]
## Type issue
Gevonden bij implementatie mapping BIS -> BRO

## Waar
Codelijst 36. Kleur (blz. 150)

## Samenvatting
Sommige Munsell kleurencodes  komen twee keer in de codelijst voor

## Beschrijving
Sommige Munsell kleurencodes  komen twee keer in de codelijst voor, soms bij dezelfde kleurtekst (5GY 5/2 bij grijsGroen en 5B 5/1 bij blauwGrijs), maar soms ook bij verschillende kleurteksten (5YR 8/1 bij wit en bij rozeGrijs).

## Oplossingsrichting
Catalogus aanpassen, en kies misschien een beter controleerbaar formaat (bv simpele hue,value,chroma, kleur tabel), iets langer (jammer) maar wel beter controleerbaaren bruikbaar in voor bouwers. Dus tijd verdient zich terug.

**Comment by BregjeBrugman** [comment]
- dubbeling 5GY 5/2 bij grijsGroen opgelost in versie 2.099 (ter vaststelling) dd 28-juli-2022 (wordt versie 2.1). Gegeven alleen van toepassing op SFR
- dubbeling 5B 5/1 bij blauwGrijs opgelost in versie 2.099 (ter vaststelling) dd 28-juli-2022 (wordt versie 2.1). Gegeven alleen van toepassing op SFR
- dubbeling 5YR 8/1 bij wit en bij rozeGrijs opgelost in versie 2.099 (ter vaststelling) dd 28-juli-2022 (wordt versie 2.1). Gegeven alleen van toepassing op SFR
