### ISSUE TITLE
waardelijst Kleur - kleuren ontbreken in omschrijving

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#18]
## Type issue
Gevonden tijdens implementatie mapping BIS -> BRO

## Waar
Codelijst 36. Kleur (blz. 150)
## Samenvatting
er ontbreken munsel kleur vertalingen

## Beschrijving
De opgegeven codelijst is onvolledig. Er zijn legitieme Munsellkleuren in het veldboekje (1975 EDITION) die niet in deze lijst zijn opgenomen. Enkele voorbeelden:

| HUE	| VALUE	| CHROMA
| ---- | ---- | ---- |
| 2.5YR	| 2.5	| 0| 
| 2.5YR	| 3	| 2| 
| 7.5YR	| 2	| 0| 
|7.5YR	|3|	0 |

Verder bestaat er naast de Munsell Soil Color Charts (1975 EDITION) een oudere versie van het veldboekje (1954 EDITION) met Munsellkleuren die in value soms iets afwijken (2 i.p.v. 2.5) van de nieuwere versie:

| HUE	| VALUE	| CHROMA| 	Waarde| 
| ---- | ---- | ---- | ---- |
| 10R	| 2	| 1	| 	roodZwart| 
| 10R	| 2	| 2	| 	donkerbruinRood| 
| 2.5YR	| 2	| 0	| 	??| 
| 2.5YR	| 2	| 2	| 	donkerbruinRood| 
| 2.5YR	| 2	| 4	| 	donkerroodBruin| 
| 5YR	| 2	| 1	| 	roodZwart| 
| 5YR	| 2	| 2	| 	donkerbruinRood| 
| 5YR	| 4	| 8	| 	geelRood?| 
| 5Y	2	| 1| 		|  zwart | 
| 5Y	2	| 2| 		|  zwart| 

## Oplossingsrichting
Vul de lijst in de catalogus aan tot deze compleet is.

**Comment by yke** [comment]
Toevoeging 20 oktober

De volgende kleuren komen voor in BIS maar kunnen nog niet worden gemapped

|HUE|VALUE|CHROMA|IMBRO|IMBRO_A|CODE|
| ---- |---- |---- |---- |---- |---- |
|10YR|2.5|0|J|J|Geen vertaling in catalogus|
|10YR|4|0|J|J|Geen vertaling in catalogus|
|10YR|6|0|J|J|Geen vertaling in catalogus|
|2.5Y|2|0|J|J|Geen vertaling in catalogus|
|2.5Y|2|1|J|J|Geen vertaling in catalogus|
|2.5Y|3|0|J|J|Geen vertaling in catalogus|
|2.5YR|2|0|J|J|Geen vertaling in catalogus|
|2.5YR|2|1|J|J|Geen vertaling in catalogus|
|2.5YR|2|2|J|J|Geen vertaling in catalogus|
|2.5YR|5|0|J|J|Geen vertaling in catalogus|
|5B|2|4|J|J|Geen vertaling in catalogus|
|5B|4|2|J|J|Geen vertaling in catalogus|
|5Y|2|0|J|J|Geen vertaling in catalogus|
|5Y|2|1|J|J|Geen vertaling in catalogus|
|5Y|2|2|J|J|Geen vertaling in catalogus|
|5Y|4|0|J|J|Geen vertaling in catalogus|
|5Y|4|8|J|J|Geen vertaling in catalogus|
|5Y|6|0|J|J|Geen vertaling in catalogus|
|5YR|2|1|J|J|Geen vertaling in catalogus|
|5YR|2|2|J|J|Geen vertaling in catalogus|
|5YR|2|3|J|J|Geen vertaling in catalogus|
|5YR|2.5|0|J|J|Geen vertaling in catalogus|
|5YR|3|0|J|J|Geen vertaling in catalogus|
|5YR|3|6|J|J|Geen vertaling in catalogus|
|5YR|4|0|J|J|Geen vertaling in catalogus|
|5YR|4|8|J|J|Geen vertaling in catalogus|
|7.5YR|2|0|J|J|Geen vertaling in catalogus|
|7.5YR|2|3|J|J|Geen vertaling in catalogus|
|7.5YR|3|0|J|J|Geen vertaling in catalogus|
|7.5YR|3|6|J|J|Geen vertaling in catalogus|
|7.5YR|4|8|J|J|Geen vertaling in catalogus|
|7.5YR|5|0|J|J|Geen vertaling in catalogus|
|N|2||J|J|Geen vertaling in catalogus|
|N|2.5||J|J|Geen vertaling in catalogus|
|10R|2|1|J|J|Geen vertaling in catalogus|
|10R|2|2|J|J|Geen vertaling in catalogus|
|10YR|2|0|J|J|Geen vertaling in catalogus|
|10YR|2|6|J|J|Geen vertaling in catalogus|
|10YR|2.5|3|J|J|Geen vertaling in catalogus|
|10YR|2.5|4|J|J|Geen vertaling in catalogus|
|10YR|3|0|J|J|Geen vertaling in catalogus|
|10YR|4|8|J|J|Geen vertaling in catalogus|
|10YR|5|0|J|J|Geen vertaling in catalogus|
|2.5Y|2|2|J|J|Geen vertaling in catalogus|
|2.5Y|2.5|2|J|J|Geen vertaling in catalogus|
|2.5Y|4|0|J|J|Geen vertaling in catalogus|
|2.5Y|5|0|J|J|Geen vertaling in catalogus|
|2.5Y|6|0|J|J|Geen vertaling in catalogus|
|2.5Y|7|0|J|J|Geen vertaling in catalogus|
|2.5YR|2|3|J|J|Geen vertaling in catalogus|
|2.5YR|2|4|J|J|Geen vertaling in catalogus|
|2.5YR|2.5|0|J|J|Geen vertaling in catalogus|
|2.5YR|3|0|J|J|Geen vertaling in catalogus|
|2.5YR|3|2|J|J|Geen vertaling in catalogus|
|2.5YR|3|8|J|J|Geen vertaling in catalogus|
|5BG|4|2|J|J|Geen vertaling in catalogus|
|5GY|2|1|J|J|Geen vertaling in catalogus|
|5GY|2|4|J|J|Geen vertaling in catalogus|
|5GY|2|6|J|J|Geen vertaling in catalogus|
|5Y|2|4|J|J|Geen vertaling in catalogus|
|5Y|3|3|J|J|Geen vertaling in catalogus|
|5YR|2|0|J|J|Geen vertaling in catalogus|
|5YR|2|4|J|J|Geen vertaling in catalogus|
|5YR|2|6|J|J|Geen vertaling in catalogus|
|5YR|2.5|2|J|J|Geen vertaling in catalogus|
|5YR|3|2|J|J|Geen vertaling in catalogus|
|7.5YR|2|2|J|J|Geen vertaling in catalogus|
|7.5YR|2|4|J|J|Geen vertaling in catalogus|
|7.5YR|2|6|J|J|Geen vertaling in catalogus|
|7.5YR|2.5|0|J|J|Geen vertaling in catalogus|
|7.5YR|4|0|J|J|Geen vertaling in catalogus|

Totaal 979 lagen

**Comment by BregjeBrugman** [comment]
mapping is gemaakt samen met Ronald Harting om een eenduidige vertaling te maken bij SFR en BHR-G. Daaruit zijn 4 extra IMBRO/A waarden voor kleur toegevoegd in de werkafspraak tranche 3: donkerblauw, donkergroen, donkerpaarsRood en olijfZwart. 

Besloten is alleen de vertaling van de actuele kleurenboekjes op te nemen in de omschrijving van de kleuren. Vertalingen van "oude" codes blijft buiten de catalogus

**Comment by OnnoRoosenschoon** [comment]
Dit vinden wij een vreemde beslissing. Wat moeten wij dan met de oude Munselkleuren? Die kunnen we dan niet leveren en die gaan we dan dus niet leveren. Is dit de bedoeling?

**Comment by fterpstra** [comment]
[20210519_BHR-GT&GEO_DeKleurenlijst_RH_inclusiefSFRgemistArchief_RoHa_gevisualiseerd_besproken20210601.xlsx](https://github.com/BROprogramma/SFR/files/7506103/20210519_BHR-GT.GEO_DeKleurenlijst_RH_inclusiefSFRgemistArchief_RoHa_gevisualiseerd_besproken20210601.xlsx)
De mapping is gemaakt en hoewel niet onderdeel van de catalogus kan hij wel gebruikt worden om oude munsel kleuren te vertalen naar de catalogus
