### ISSUE TITLE
Codelijst 38.Landschapselement (blz. 158)

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#19]
## Type issue
Gevonden door Fokke Brouwer bij implementatie mapping BIS -> BRO

## Waar
De waarden “rivierduinBegraven” en rivierduinNietBegraven “” hebben in de codelijst dezelfde omschrijving

## Samenvatting
[Korte tekst van de melding. Bijvoorbeeld: 'De tekst is hier onduidelijk.']

## Beschrijving
De waarden “rivierduinBegraven” en rivierduinNietBegraven “” hebben in de codelijst dezelfde Omschrijving. De Omschrijving van “rivierduinNietBegraven” is fout. Deze moet zijn:
Natuurlijk landschapselement. Niet-overdekt rivierduin.

## Oplossingsrichting
Aanpassen in catalogus

**Comment by BregjeBrugman** [comment]
aangepast in catalogus versie 1.99
