### ISSUE TITLE
Tekstuele verbetering 0.99 catalogus

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/SPR#2]
## Type issue
Bevinding vanuit WENR

## Waar
catalogus 0.99 sectie 9.0 wandbeschrijving -> toelichting (pag 35)

## Samenvatting
Kleine tekstuele verbetering 

## Beschrijving
Toelichting
De beschrijving wordt gedaan door ervaren veldbodemkundigen en ter ondersteuning van schattingen worden referentiemonsters gebruikt. ->
Toelichting
De beschrijving wordt gedaan door ervaren veldbodemkundigen en ter ondersteuning van schattingen worden **vaak** referentiemonsters gebruikt.

## Oplossingsrichting
tekst aanpassen in volgende versie catalogus

**Comment by BregjeBrugman** [comment]
opgenomen in versie 1.99
