### ISSUE TITLE
waardelijst MunsellZuiverheid - waarde 0 ontbreekt

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#20]
## Type issue
Gevonden tijdens implementatie mapping BIS -> BRO

## Waar
Codelijst 46.MunsellZuiverheid (blz. 162)

## Samenvatting
Waarde 0 ontbreekt in de codelijst.

## Beschrijving
Waarde 0 ontbreekt in de codelijst.

## Oplossingsrichting
aanpassen in codelijst

**Comment by BregjeBrugman** [comment]
IMBRO/A waarde 0 is toegevoegd via de werkafspraak tranche 3
