### ISSUE TITLE
waardelijst OrganischeStofGehalteklasseNEN5104 - onderscheid nietHumeus en zwakHumeus

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#21]
## Type issue
Gevonden tijdens implementatie mapping BIS -> BRO

## Waar
Codelijst 51.OrganischeStofGehalteklasse (blz. 162)

## Samenvatting
Het apart onderscheiden van de waarde “nietHumeus” (Organische stof is niet aanwezig) is een farce!! Theoretisch kun je niet vaststellen (in verband met detectielimiet) dat er in een grond exact 0% organische stof aanwezig is. De enige juiste benadering is dat je dit onderbrengt in de klasse “zwakHumeus”.

## Beschrijving
Het apart onderscheiden van de waarde “nietHumeus” (Organische stof is niet aanwezig) is een farce!! Theoretisch kun je niet vaststellen (in verband met detectielimiet) dat er in een grond exact 0% organische stof aanwezig is. De enige juiste benadering is dat je dit onderbrengt in de klasse “zwakHumeus”.

## Oplossingsrichting
Overleg met Fokke Brouwer.

**Comment by BregjeBrugman** [comment]
In een volgende versie van de catalogus komt de waarde nietHumeus te vervallen. De dataleverancier zal (en mag) de waarde nietHumeus niet gebruiken. Wanneer het wel voorkomt zal de waarde gecorrigeerd moeten worden naar nietHumeus

**Comment by BregjeBrugman** [comment]
Opgenomen als uitgewerkt issue (nr. 1) in overzicht openstaande punten: 20220622_Openstaande punten_overzicht_SFRenBHRP.xlsx
Issue wordt hier gesloten
