### ISSUE TITLE
waardelijst Vlekkleur - geelTotLichtgeel

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#22]
## Type issue
Gevonden tijdens implementatie mapping BIS -> BRO

## Waar
Codelijst 71.Vlekkleur (blz. 180)

## Samenvatting
Omschrijving bij de waarde “geelTotLichtgeel”  De vlekken … in kattenklei  katteklei

## Beschrijving
Omschrijving bij de waarde “geelTotLichtgeel”  De vlekken … in kattenklei  katteklei

## Oplossingsrichting
Aanpassen

**Comment by BregjeBrugman** [comment]
verwerkt in versie 2.099 (ter vaststelling) dd 28-juli-2022 (wordt versie 2.1).
Gegeven alleen van toepassing op SFR
