### ISSUE TITLE
Uiteenvallend (attribuut van bodemaggregaat)

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#23]
## Type issue
Gevonden tijdens implementatie ,apping BIS -> BRO

## Waar
Uiteenvallend (par. 9.11.6, blz. 83)

## Samenvatting
In de catalogus bij dit attribuut een Toelichting toevoegen dat het bij dit gegeven gaat om kluiten, ontstaan bij de jaarlijkse, mechanische grondbewerking (bijv. ploegen of vaste-tandcultivator). 

## Beschrijving
In de catalogus bij dit attribuut een Toelichting toevoegen dat het bij dit gegeven gaat om kluiten, ontstaan bij de jaarlijkse, mechanische grondbewerking (bijv. ploegen of vaste-tandcultivator). 

## Oplossingsrichting
Aanpassen in catalogus

**Comment by BregjeBrugman** [comment]
Toelihcting toegevoegd in versie 2.099 (ter vaststelling) dd 28-juli-2022 (wordt versie 2.1).
Gegeven alleen van toepassing op SFR
