### ISSUE TITLE
Gemengd (par. 9.3.8, blz. 53)

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#24]
## Type issue
Gevonden tijdens implementatie mapping BIS -> BRO

## Waar
Gemengd (par. 9.3.8, blz. 53)

## Samenvatting
is voor kwaliteitsregime IMBRO/A nu HOR_CODE like “-/-” maar dit gaat niet altijd even lekker! Ook de vertaling van de BIS_Horizontcode naar de BRO_Horizontcode is wankel omdat in BRO geen “/” is toegestaan. Sowieso is de BRO-lijst met horizontcodes toe aan inspectie.

## Beschrijving
is voor kwaliteitsregime IMBRO/A nu HOR_CODE like “-/-” maar dit gaat niet altijd even lekker! Ook de vertaling van de BIS_Horizontcode naar de BRO_Horizontcode is wankel omdat in BRO geen “/” is toegestaan. Sowieso is de BRO-lijst met horizontcodes toe aan inspectie.

## Oplossingsrichting
Overleg met Fokke Brouwer.

**Comment by BregjeBrugman** [comment]
voor de / is de laagcomponent gemodelleerd (volumepercentage mag dan weg blijven)
