### ISSUE TITLE
Beworteld (blz. 54)

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#25]
## Type issue
Gevonden tijdens implementatie mapping BIS -> BRO

## Waar
Beworteld (blz. 54)

## Samenvatting
Bij beworteld = “ja”  moeten zowel ‘wortels gelijkmatig verdeeld’ en ‘hoeveelheidsklasse wortels’ zijn ingevuld. Dit is in principe ook logisch. Echter bij IMBRO/A data komt het soms voor dat de ene wel (‘wortels gelijkmatig verdeeld’ of ‘hoeveelheidsklasse wortels’) en de ander niet is ingevuld met als gevolg dat de waarde van het wel ingevulde attribuut komt te vervallen want zoals het nu is geprogrammeerd is het beide of niets (leidt tot enig informatieverlies).

## Beschrijving
Bij beworteld = “ja”  moeten zowel ‘wortels gelijkmatig verdeeld’ en ‘hoeveelheidsklasse wortels’ zijn ingevuld. Dit is in principe ook logisch. Echter bij IMBRO/A data komt het soms voor dat de ene wel (‘wortels gelijkmatig verdeeld’ of ‘hoeveelheidsklasse wortels’) en de ander niet is ingevuld met als gevolg dat de waarde van het wel ingevulde attribuut komt te vervallen want zoals het nu is geprogrammeerd is het beide of niets (leidt tot enig informatieverlies).

## Oplossingsrichting
Contact Fokke Brouwer

**Comment by BregjeBrugman** [comment]
Is opgelost in versie 1.99 door toevoeging waarde onbekend voor beide gegevens
