### ISSUE TITLE
Bijzonder materiaal (attribuut van homogeen materiaal)

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#26]
## Type issue
Gevonden tijdens implementatie mapping BIS -> BRO

## Waar
Bijzonder materiaal (blz. 56)

## Samenvatting
Zowel bij de Definitie als bij de Toelichting tekst toevoegen: … niet als grond of gesteente …  … niet als strooisel, grond of gesteente …

## Beschrijving
Zowel bij de Definitie als bij de Toelichting tekst toevoegen: … niet als grond of gesteente …  … niet als strooisel, grond of gesteente …

## Oplossingsrichting
Aanpassen catalogus

**Comment by BregjeBrugman** [comment]
Toelichting aangepast in versie 2.099 (ter vaststelling) dd 28-juli-2022 (wordt versie 2.1).
Gegeven alleen van toepassing op SFR
