### ISSUE TITLE
Bijzonder bestanddeel (attribuut van Grond)

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#27]
## Type issue
Gevonden tijdens implementatie mapping BIS -> BRO

## Waar
Bijzonder bestanddeel (par. 9.5.4, blz. 61)

## Samenvatting
[Korte tekst van de melding. Bijvoorbeeld: 'De tekst is hier onduidelijk.']

## Beschrijving
Heeft in de catalogus versie 0.99 nu Kardinaliteit van 1 maar dit moet worden opgehoogd naar 1…n want het kan meer waarden herbergen.

## Oplossingsrichting
Aanpassen catalogus.

**Comment by BregjeBrugman** [comment]
aangepast in catalogus versie 1.99
