### ISSUE TITLE
Bodemleven (par. 9.3.10, blz. 54)

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#29]
## Type issue
Gevonden tijdens implementatie mapping BIS -> BRO 

## Waar
Bodemleven (par. 9.3.10, blz. 54)

## Samenvatting
Heeft in de catalogus versie 0.99 nu Kardinaliteit van 1 maar dit moet worden opgehoogd naar 1…n want het kan meer waarden herbergen.

## Beschrijving
Heeft in de catalogus versie 0.99 nu Kardinaliteit van 1 maar dit moet worden opgehoogd naar 1…n want het kan meer waarden herbergen.

## Oplossingsrichting
In conceptuele model (plaatje) 1..3 catalogus aanpassen.

**Comment by BregjeBrugman** [comment]
aangepast in catalogus versie 1.99
