### ISSUE TITLE
tekstuele verbetering 0.99 catalogus

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/SPR#3]
## Type issue
Bevinding vanuit WENR

## Waar
catalogus 0.99 sectie 9.7.3 antropogeen -> toelichting (pag 53)

## Samenvatting
Kleine tekstuele verbetering 

## Beschrijving
Toelichting
Het materiaal waar de laag uit bestaat kan door de mens van elders zijn aangevoerd, maar ook door de mens van een andere diepte zijn weggehaald, bijvoorbeeld door ploegen. ->
Toelichting
Het materiaal waar de laag uit bestaat kan door de mens van elders zijn aangevoerd, maar ook door de mens van een andere diepte zijn weggehaald, bijvoorbeeld door **diep** ploegen.

## Oplossingsrichting
tekst aanpassen in volgende versie catalogus

**Comment by BregjeBrugman** [comment]
opgenomen in versie 1.99
