### ISSUE TITLE
Fractieverdeling bepaald (par. 9.0.6, blz. 38)

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#30]
## Type issue
Gevonden tijdens implementatie mapping BIS -> BRO

## Waar
Fractieverdeling bepaald (par. 9.0.6, blz. 38)

## Samenvatting
Regels: Wanneer de waarde van het attribuut kwaliteitsregime van de entiteit Wandonderzoek gelijk is aan IMBRO, is de waarde van het gegeven ja. Dit houdt voor ‘IMBRO’-data dus in dat bij grond altijd een verplichte invulling geldt van lutumgehalte, siltgehalte en verdeling fijne fractie.

Het schatten en zeker ook het analyseren van lutum, silt en zandfractie in grond met een (zeer) hoog organische-stofgehalte (bodemkundige grondsoort = ‘veen’) is uiterst moeilijk omdat dit moet gebeuren op de minerale delen dus pas nadat deze grondsoort van zijn hoge organische-stofgehalte is ontdaan. Ter discussie staan het nut van vermelding van bovengenoemde waarden bij deze grondsoort en de ‘juridische’ correctheid in verband met detectielimiet van de grondschatters c.q. van de labmethode. Bodemkarteerders hebben een sterke voorkeur om bij deze specifieke grondsoort (bodemkundige grondsoort = ‘veen’) ook voor kwaliteitsregime IMBRO  fractieverdeling bepaald = nee toe te staan.

## Beschrijving
Regels: Wanneer de waarde van het attribuut kwaliteitsregime van de entiteit Wandonderzoek gelijk is aan IMBRO, is de waarde van het gegeven ja. Dit houdt voor ‘IMBRO’-data dus in dat bij grond altijd een verplichte invulling geldt van lutumgehalte, siltgehalte en verdeling fijne fractie.

Het schatten en zeker ook het analyseren van lutum, silt en zandfractie in grond met een (zeer) hoog organische-stofgehalte (bodemkundige grondsoort = ‘veen’) is uiterst moeilijk omdat dit moet gebeuren op de minerale delen dus pas nadat deze grondsoort van zijn hoge organische-stofgehalte is ontdaan. Ter discussie staan het nut van vermelding van bovengenoemde waarden bij deze grondsoort en de ‘juridische’ correctheid in verband met detectielimiet van de grondschatters c.q. van de labmethode. Bodemkarteerders hebben een sterke voorkeur om bij deze specifieke grondsoort (bodemkundige grondsoort = ‘veen’) ook voor kwaliteitsregime IMBRO  fractieverdeling bepaald = nee toe te staan.

## Oplossingsrichting
Overleg dit even met Fokke Brouwer

**Comment by BregjeBrugman** [comment]
Opgenomen als funnel issue (nr. 3) in overzicht openstaande punten: 20220622_Openstaande punten_overzicht_SFRenBHRP.xlsx
Issue wordt hier gesloten
