### ISSUE TITLE
Codelijst 18.Brokje (blz. 127)

### ISSUE THREAD

**Issue by brouw028** [BROprogramma/SPR#31]
## Type issue
Er ontbreekt een waarde in de codelijst 18.Brokje

## Waar
Codelijst 18.Brokje (blz. 127)

## Samenvatting
De waarde "oerbrokjes" ontbreekt

## Beschrijving
De waarde "oerbrokjes" ontbreekt met de Omschrijving "De grond bevat brokjes oer." Oer kan in lagen (Bijzonder materiaal), in laagjes (GelaagdeInhomogeniteit) maar ook in brokjes voorkomen.

## Oplossingsrichting
Nieuwe waarde "oerbrokjes" aan codelijst 18.Brokje toevoegen.

**Comment by BregjeBrugman** [comment]
waarde toegevoegd in werkafspraak tranche 3 (nr. 9)
