### ISSUE TITLE
geschatte verzadigde doorlatendheid (attribuut van Laagcomponent)

### ISSUE THREAD

**Issue by Naj6jep** [BROprogramma/SPR#32]
## Type issue
Review sessie 

## Waar
Opbouw en bereik van geschatte verzadigde doorlatendheid: par.9.12.4, blz. 85

## Samenvatting
De opbouw en het bereik matchen niet.

## Beschrijving
De opbouw is 1.2 en het waardebereik is 0 tot 10. Het getal 10 mag niet onder de gegeven opbouw, 9.99 wel. Dit is niet consequent. 

## Oplossingsrichting
Het waardebereik en de opbouw afstemmen.

**Comment by WijnandvanRiel** [comment]
Blijft ongewijzigd tot er vanuit het werkveld geschatte waardes van 10 aangeleverd moeten gaan worden.

**Comment by BregjeBrugman** [comment]
Was al verwerkt in versie 2.0 (meetwaarde 2.2).
Gegeven alleen van toepassing bij SFR
