### ISSUE TITLE
Element landschapselement verplicht voor WENR profielkuilen via busines rule

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#35]
## Type issue
Review sessie , eigenlijk komt het voort uit testen van leveren door WENR. 

Dit komt voor bij meer dan 2750 profielen grote overlap met #38

## Waar
element landschapselement

## Samenvatting
Het element landschapselement is optioneel (card 0..1) maar via een businessrule is het voor ons als nog verplicht geworden (wij leveren bodemkaartNederlandEenheidType als waarde)
 
Het gegeven is aanwezig wanneer de waarde van het attribuut kader inwinning van de entiteit Wandonderzoek gelijk is aan bodemkaartNederland, bodemkaartNederlandEenheidType. In andere gevallen mag het gegeven ontbreken. 
 
Dit betekent dat wij op dit moment geen enkel profiel kunnen leveren. Volgens Fokke zou hierbij moeten dat het 
•	Of voor IMBRO/A toch leeg mag blijven
•	Of voor IMBRO/A staan we onbekend toe

## Beschrijving
Zie samenvatting

## Oplossingsrichting
•	Voor IMBRO/A mag landschapselement toch leeg mag blijven
•	Voor  IMBRO/A voegen we onbekend toe aan de codelijst voor landschapselement

**Comment by fterpstra** [comment]
is in de 1.9 catalogus opgelost door bij het attribuut landschapselement van de entiteit Terreintoestand de tagged value Mogelijk geen waarde op Ja te zetten en de volgende IMBRO/A regel toe te voegen: 
Naast de IMBRO waardes mag het gegeven ontbreken.

**Comment by sjaakd** [comment]
Merk op: de catalogus tekst lijkt fout.. Huidige aanname voor implementatie: 

https://github.com/BROprogramma/SFR/issues/38

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
