### ISSUE TITLE
Grond.bodemkundige grondsoort (Soil.pedologicalSoilName) = moerigMateriaal waarde is niet correct: komt niet voor in de codelijst.

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#37]
## Type issue
Review sessie , gedetecteerd tijdens testen door WENR

## Waar
grond.bodemkundige grondsoort (Soil.pedologicalSoilName)

## Samenvatting
moerigMateriaal waarde is al in BHR-P toegevoegd omdat WENR vooral bij oude profielen te weinig  informatie heeft om een nauwkeuriger en betere waarde toe te kennen. Deze waarde staat niet in de catalogi van noch SFR noch BHR-P maar wordt bij BHR-P wel degelijk gebruikt.

## Beschrijving
Zie samenvatting

## Oplossingsrichting
Toevoegen aan codelijst net als bij BHR-P

**Comment by fterpstra** [comment]
zit nog niet in de consultatie versie maar we nemen hem mee in de verwerking naar 0.99

**Comment by OnnoRoosenschoon** [comment]
2 weken geleden heeft Yke van Randen contact gehad met Sjaak Derksen en van hem begrepen dat kleiigeLeem en MoerigMateriaal  zijn toegevoegd aan de catalogus voor BHR-p. Dit moet ook gebeuren voor SFR.

**Comment by BregjeBrugman** [comment]
waarde is opgenomen in de werkafspraak tranche 3

**Comment by OnnoRoosenschoon** [comment]
kleiigeLeem en MoerigMateriaal zijn dus beide toegevoegd aan de catalogus voor zowel BHR-p als SFR? Graag bevestiging

**Comment by fterpstra** [comment]
het staat als volgt in de werkafspraak: 
	Bij BHR-P is in de waardelijst BodemkundigeGrondsoortnaam de waarde kleiigeLeem opgenomen.
	Bij BHR-P is in de waardelijst BodemkundigeGrondsoortnaam de IMBRO/A waarde moerigMateriaal opgenomen.
	Bij SFR is in de waardelijst BodemkundigeGrondsoort is de waarde kleiigeLeem opgenomen.
	Bij SFR is in de waardelijst BodemkundigeGrondsoort de IMBRO/A waarde moerigMateriaal opgenomen.
Dus dit is gebeurd
