### ISSUE TITLE
Melding uit validatie service Bodemclassificatie.afwijkend grondwaterregime (SoilClassification.anomalousGroundwaterRegime) ontbreekt: 

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#38]
## Type issue
Review sessie, kwam naar voren tijdens leveren, treedt op bij 2660 profielen dus grote overlap met #35 

## Waar
Bodemclassificatie.afwijkend grondwaterregime

## Samenvatting
Cataogus is te streng. De  tekst 'in alle andere gevallen is het gegeven aanwezig'  moet weg conform voorstel Janneke

## Beschrijving
[Lange omschrijving van de melding. Probeer zo concreet mogelijk het probleem of je suggestie voor verbetering te beschrijven. Bijvoorbeeld: 'Het is onduidelijk wat er precies met ... bedoeld wordt'.]

## Oplossingsrichting
De  tekst 'in alle andere gevallen is het gegeven aanwezig'  moet weg conform voorstel Janneke

**Comment by WijnandvanRiel** [comment]
De tekst " In andere gevallen is het gegeven aanwezig." uit de IMBRO/A regels is uit de gegevens definitie verwijderd. De wijziging wordt zichtbaar in de eerstvolgende catalogus.

**Comment by sjaakd** [comment]
De verwachtte uitwerking is:

![image](https://user-images.githubusercontent.com/6173283/69611344-dae16a00-102d-11ea-996e-9bd991c71e16.png)

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
