### ISSUE TITLE
Typefout in lijst businessrule bij "ondergrond duinvaaggrond"

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#39]
## Type issue
Review sessie [verwijderen wat niet van toepassing is]

## Waar
Regel bij "ondergrond duinvaaggrond"

## Samenvatting
Er is een regel die als volgt luidt

```
Het gegeven is aanwezig wanneer de waarde van het attribuut bodemklasse gelijk is aan duinvaaggrond, duinvaaggrondMatigHumusarm, duinvaaggrondUiterstHumusarm of duinvaaaggrondZeerHumusarm. In andere gevallen ontbreekt het gegeven.
```
duinvaaag bevat een a teveel.

## Beschrijving
Zie samenvatting

## Oplossingsrichting
duinvaaag vervangen door duinvaag

**Comment by WijnandvanRiel** [comment]
duinvaaaggrondZeerHumusarm is in de gegevens definitie gewijzigd. De wijziging wordt zichtbaar in de eerstvolgende catalogus.

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
