### ISSUE TITLE
tekstuele verbetering 0.99 catalogus

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/SPR#4]
Type issue
Bevinding vanuit WENR

Waar
catalogus 0.99 sectie 9.5.3 grondsoort NEN5104 -> toelichting (pag 61)

Samenvatting
Kleine tekstuele verbetering

Beschrijving
Toelichting
De naam is afgeleid uit de waarden voor de fractieverdeling. Wanneer de fracties niet volledig zijn gespecificeerd kan de naam niet worden afgeleid. Voor grind wordt alleen de naam van de hoofdgrondsoort (grind) gegeven en als het grind vooral uit schelpmateriaal bestaat geldt dat als de naam van de grondsoort. ->
Toelichting
De naam is afgeleid uit de waarden voor de fractieverdeling. Wanneer de fracties niet volledig zijn gespecificeerd kan de naam niet worden afgeleid. Voor grind wordt alleen de naam van de hoofdgrondsoort (grind) gegeven en als **de grond** vooral uit schelpmateriaal bestaat geldt dat als de naam van de grondsoort.

Oplossingsrichting
tekst aanpassen in volgende versie catalogus

**Comment by BregjeBrugman** [comment]
opgenomen in versie 1.99
