### ISSUE TITLE
Codelijst Bodemclassificatie.textuurklasse 

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#40]
## Type issue
Review sessie, tijdens testen WENR

## Waar
Validatie door bronhouderportaal levert meldingen als 
* Bodemclassificatie.textuurklasse (SoilClassification.textureClass) = 'zavelMatigLicht' waarde is niet correct: komt niet voor in de codelijst.
* Bodemclassificatie.textuurklasse (SoilClassification.textureClass) = 'zavelZeerLicht' waarde is niet correct: komt niet voor in de codelijst.
* Bodemclassificatie.textuurklasse (SoilClassification.textureClass) = 'zavelZwaar' waarde is niet correct: komt niet voor in de codelijst.

## Beschrijving
Zie samenvatting

## Oplossingsrichting
zavelMatigLichtkomt,zavelZeerLicht,zavelZwaar komen wel voor in codelijst (catalogus p 174) dus validatie aanpassen

**Comment by BregjeBrugman** [comment]
waarden zijn opgenomen.
