### ISSUE TITLE
decimalen bij upper/lowerBounday litterlayer

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#41]
## Type issue
Review sessie , gevonden tijdens testen

## Waar
upper/lowerBounday litterlayer

## Samenvatting
In een aantal gevallen zijn lagen onderscheiden in een profielkuil waarbij de diepte tot op 0.5 cm nauwkeurig gemeten wordt. Afronden naar 2 decimalen zorgt ervoor dat de dikte van de laag 0 wordt.

Er is een laag met als bovengrens -0.09 m en als ondergrens -0.085 m. na afronden op 2 decimalen worden beide waarden -0.09 m en dat resulteert in een dikte van 0 m en een foutmelding.

## Beschrijving
Zie samenvatting

## Oplossingsrichting
Pas dieptes voor litterlayers aan zodat 3 decimalen toegestaan zijn.

**Comment by BregjeBrugman** [comment]
aangepast in werkafspraak tranche 3

**Comment by OnnoRoosenschoon** [comment]
Wanneer worden deze werkafspraken geimplementeerd?

**Comment by fterpstra** [comment]
het staat als volgt in de werkafspraak: 
	Bij BHR-P is het domein van het attribuut bovengrens (attribuut van Strooisellaag) Meetwaarde 1.3
	Bij BHR-P is het domein van het attribuut ondergrens (attribuut van Strooisellaag) Meetwaarde 1.3
	Bij SFR is het domein van het attribuut bovengrens (attribuut van Strooisellaag) Meetwaarde 1.3
	Bij SFR is het domein van het attribuut ondergrens (attribuut van Strooisellaag) Meetwaarde 1.3
en als het goed is dus ook zo geimplementeerd

**Comment by fterpstra** [comment]
Volgens Yke lost dit nog niet alles op. De begindiepte van de strooisellaag niet een geheel aantal cm boven maaiveld is, werkt dit niet. Oftewel als de strooisellaag is uitgedrukt in mm.

Uit WENR GIT https://git.wur.nl/BRO/bkr-kuil/-/issues/208

Antwoord Fokke 21-1-2021: Vorige week afspraak met Bregje (TNO) gemaakt dat we zowel voor BHR-p als voor SFR alle lagen gaan opslaan met drie decimalen. Omdat de dimensie van deze dieptes in meters is, kunnen we binnenkort (na aanpassingen van het bouwteam) de lagen dus in mm nauwkeurig gaan aanleveren. 

Volgens WENR zoude alle begin en einddieptes 
 zoals https://docs.geostandaarden.nl/bro/sfr/#detail_attribute_Model_Wandontsluiting_einddieptewand 3 decimalen moeten krijgen, dit blokkeert ruim 500 beschrijvingen. Wordt door WENR een servicedeskmelding van gemaakt.
