### ISSUE TITLE
Terreintoestand.vegetatietype lichtBosBronsmosBochtigeSmeleStruisgassen waarde is niet correct

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#42]
## Type issue
Review sessie , kwam naar voren tijdens testen.

## Waar
Terreintoestand.vegetatietype

## Samenvatting
Bronhouderportaal validatie geeft een melding dat "lichtBosBronsmosBochtigeSmeleStruisgassen" een incorrecte waarde is maar deze staat zo in de catalogus (p 178).

In de SFR codelijst staat terecht (wie de correctie heeft gedaan is onbekend) lichtBosBronsmosBochtigeSmeleStruisg**r**assen ipv lichtBosBronsmosBochtigeSmeleStruisgassen. WENR heeft haar vertaling aangepast en dit issue treedt nu niet meer op.

## Beschrijving
Zie samenvatting

## Oplossingsrichting
Codelijst in catalogus anpassen.

**Comment by RuudMutsaers** [comment]
is inmiddels opgelost in nieuwe catalogus

**Comment by BregjeBrugman** [comment]
aangepast in catalogus versie 1.99
