### ISSUE TITLE
Onduidelijkheid over Diakrieten (Löss Loess of Loss)

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/SPR#43]
## Type issue
Bevinding uit implementatie

## Waar
codelijsten 5.4.15 5.4.20 in HTML versie https://broprogramma.github.io/SFR/

## Samenvatting
Waarden in codelijsten in de catalogus bevatten diakrieten terwijl dit in de implementatie niet ondersteund wordt. Er is onduidelijkheid wat nu de juiste spelling is die tijdens implementatie gebruikt moet worden.

## Beschrijving
Op dit moment heb zijn er bij WENR zo’n 404 lagen bij 144 profielen (ongeveer 5% dus) waar dit speelt. Duidelijkheid over de juiste spelling is nodig voor het implementeren van een oplossing.

## Oplossingsrichting
De spelling van waarden in de codelijsten in de catalogus wordt aangepast naar een spelling zonder diakrieten "Loss" of "Loess". Op basis hiervan worden ook de codelijsten die de LV-BRO hanteerd aangepast.

**Comment by yke** [comment]
De WENR SFR appliatie gebruikte hier de BHR-P software en daarin wordt löss geleverd. We krijgen dus nu de situatie dat BHR-P löss levert en SFR loess.

Lijkt me niet wenselijk en is niet consistent.

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
