### ISSUE TITLE
codelijst en catalogus inconsistent

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#45]
## Type issue
.Review sessie Bevinding tijdens testen

## Waar
Vegetatie type p 177.

## Samenvatting

In de codelijst van SFR (https://github.com/BROprogramma/SFR/blob/gh-pages/XSD/SFR%20Codelijsten.csv) staat terecht de waarde lichtBosBronsmosBochtigeSmeleStruisg**r**assen, echter in de catalogus staat de waarde lichtBosBronsmosBochtigeSmeleStruisgassen, conform de documentatie van WENR.

## Oplossingsrichting
In catalogus aanpassen naar lichtBosBronsmosBochtigeSmeleStruisgrassen

**Comment by RuudMutsaers** [comment]
Is inmiddels opgelost in de nieuwe catalogus

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
