### ISSUE TITLE
Ook BHR-P

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#47]
## Type issue
Publieke consultatie

## Waar
Diverse plekken in catalogus

## Beschrijving
[Lange omschrijving van de melding. Probeer zo concreet mogelijk het probleem of je suggestie voor verbetering te beschrijven. Bijvoorbeeld: 'Het is onduidelijk wat er precies met ... bedoeld wordt'.]

## Oplossingsrichting
Meer en betere harmonisatie, aanpassen proces zodat harmonisatie een uitgangspunt is en geen actie achteraf.

**Comment by BregjeBrugman** [comment]
Opgenomen als funnel issue (nr. 12) in overzicht openstaande punten: 20220622_Openstaande punten_overzicht_SFRenBHRP.xlsx
Issue wordt hier gesloten
