### ISSUE TITLE
Analyses deel 1, 2 en 3

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/SPR#49]
## Type issue
Publieke consultatie

## Van
WEnR

## Waar
Analyses deel 1, 2 en 3

## Samenvatting
• erg veel herhaling van dezelfde eigenschappen bij de entiteiten 29, 30, 39, 64, 40, 41, 44, 47, 50, 54, 57 en verwerkingstap namelijk procedure en methode, het verschil procedurebepaling, een waarde en modellering een curve is weliswaar een essentieel verschil maar het kenmerk procedure en methode is niet wezenlijk anders. -> koppelen aan interval is onjuist, aan een interval kunnen meerdere resultaten gekoppeld zijn met elk een eigen bepaling.
• procedure en methode is bijna altijd een waarde uit een waardelijst waarvan de waarden moeten voorkomen uit een norm of praktijkrichtlijn, waarom hier geen codelijst van gemaakt met waarde ,herkomst , ...? De gebruikte norm is nu verstopt in een regel. -> voorstel: gebruik hier een codelijst met daarin ook waarde en herkomst ook om hier de norm zichtbaar te krijgen. Roept om abstractie van gemeenschappelijke gedrag naar 1 bro entiteit.
• Korrelgrootteverdeling kent veel onderverdelingen. -> Voorstel: gewoon elke verdeling heeft methode, procedure en een attribuut standaard (Ja/Nee) en een lijst fracties die elk de volgende attributen hebben : fractienaam/ fractieondergrens/ fractiebovengrens/ meetwaarde? Dit sluit ook aan bij die niet- gestandaardiseerde fractie. Dus extra codelijst korrelgrootteverdeling met als extra attribuut in die codelijst of de korrelgrootteverdeling een standaard is (of daarvan afgeleid).
• Bodem/hydro-fysische gegevens lijken redelijk compleet, bodemchemische gegevens verre van (alleen pH en organische/kool stof). Dat kan niet de bedoeling zijn van een basisregistratie. Waar haalt de gebruiker dan de andere chemische parameters op? Is dit bruikbaar? -> Voorstel: zie hieronder model GAR. ook voordeel omdat uitbreiden met meer analyses dan een aanpassing van de configuratie is terwijl structuur 100% gelijk blijft, nu is dus gedefinieerd dat er niet meer analyses komen. Uitbreiding met nieuwe analyses betekent dus hele traject weer doorlopen. Via abstractie dus flexibeler.
• Maak abstracte klasse bepaling en neem daar procedure en methode op. Alle andere bepaling erven hiervan. Laat dit SFR ontstijgen en neem dit op in brocommon. Dit geldt ook voor interval/monster. Een analyses doe je op een monster (monstername kan verschillen per registratieobject), doe je via een methode/procedure en levert een resultaat (enkelvoudig of samengesteld). Dus ook monster en resultaat kunnen abstract zijn. Sluit ook aan bij het BIT-advies.
• Tevens maakt dit BRO herkenbaarder, het is erg vreemd dat binnen de basisregistratie elk registratieobject en eigen compleet andere methode van vastleggen voor een generiek iets als analyses gebruikt. Keuze voor GAR betekent ook dat bij toevoegen van een nieuwe analyses alleen de parameterlijsten aangepast moeten worden en de structuur van het model niet wijzigt. Dit levert dus een kortere doorlooptijd van mutaties op en door het brede hergebruik wordt ook een kwaliteitsverbetering bereikt.

## Beschrijving
Alles overziend:
• lijkt de modellering voor ‘het gebruik’ zoals ook wij dat bij WENR doen onnodig complex (veel is dubbel) en onvolledig. Dit lijkt niet volgend op het BIT-advies met bestuurlijke reactie (kenmerk: 2019-0000050136 dd 29/1/2019): ‘Standaardiseer minder vergaand, zodat alle relevante gegevens worden opgenomen.’ De maatregel om tot een gewogen beslissing van de mate tot standaardisatie te komen lijkt hier niet tot uitdrukking te komen. In het scope document is met name over de detaillering en compleetheid een ander beeld geschetst. In aanvulling hierop lijkt de aanpak zoals dat bij de grondwatersamenstelling (GAR zie figuur hieronder) is gehanteerd veel beter aan te sluiten met daarbij het voordeel dat dat model zich ook wat makkelijker laat vertalen naar internationale standaarden zoals in ISO 19156 Observations & Measurements. Dit is binnen het standaardisatieteam ook al eerder besproken (overleg 1 augustus WENR-Frank/Han zie 2e figuur gebruikt als praatplaat), waarbij afgesproken is dat het model van de analyses zich eenvoudig zou moeten laten vertalen naar O&M in het technische model. Dat lijkt nu niet het geval te zijn. 
• Analyses (eigenlijk dus O&M) komen veel meer voor bij de registratieobjecten, promoveren naar BRO-Common levert veel voordeel op vorkomt inconsistentie en ambiguiteit. Groot risico nu is met de twee huidige onafhankelijke modellen dat je de kans loopt dat er na afloop weer een harmonisatie traject moet komen zoals dat nu voorgesteld is voor sfr-p en bhr-p, dus weer extra inspanning budget etc.
• De reden om af te wijken van standaarden in GAR, Gebruik van O&M, ‘compliancy’ met INSPIRE ontbreekt totaal. Dat besluit wordt nergens beargumenteerd.
• Dit model wordt omgezet naar een technisch model. Als zo'n technisch model wel volgens de normale modelleer regels gemaakt wordt dan gaat de communicatie tussen inhoudelijk experts en domeinmodelleurs, inhoudelijke experts en technisch modelleurs en tussen domein en technisch modelleurs lastiger worden met alle gevolgen van dien..

## Oplossingsrichting
Voorstel: 
Standaardiseer minder specifiek en maak het compleet met meer relevante gegevens om zo bruikbare registratieobjecten te kunnen leveren. Dit is meer gestandaardiseerd -> alles zelfde parametriseerbare structuur (circa 585 verschillende chemische stoffen) en dus minder 'hardgecodeerde' detaillering. Voorkom inconsistentie en ambiguïteit, promoveer wat BRO-algemeen is naar BRO-Common.

**Comment by BregjeBrugman** [comment]
Zie antwoord publieke consultatie: 

In dit issue zijn een aantal aspecten aangegeven. 

1. Herhaling van informatie
Voor elke bepaling is de informatie appart uitgewerkt aangezien de informatie per bepaling anders is. In sommige gevallen zijn bepaalde attributen voor meerdere bepalingen relevant. In die gevallen zal de informatie geheel of gedeeltelijk overeenkomen en dubbel aanwezig zijn in de catalogus. Echter is dit inherent aan het feit dat elke bepaling apart is uitgewerkt. 

2. Bodemchemische gegevens zijn niet compleet.
Er is in overleg met de stakeholders een prioritering aangebracht in de bepalingen die opgenomen worden in de BRO. Vanuit deze prioritering zijn zo veel mogelijk bepalingen opgenomen in deze tranche. Voor bodemchemische analyses zijn dit er inderdaad weinig. Binnen de realisatiefase was er geen ruimte om meer te realiseren. We gaan na de huidige projectfase de chemische bepalingen uitbreiden. Tezijnertijd moet opnieuw gescoped worden.

3. Gebruik O&M
Vanuit de BRO wordt zoveel mogelijk gebruik gemaakt van O&M. We hebben gepoogd O&M ondersteuning in het Logisch model(het uitwisselmodel) in te bouwen. Uit voortschreidend inzicht tijdens het standaardisatie traject bleek dat dit niet mogelijk was zonder grote aanpassingen in het conceptuele model(deze catalogus). Helaas was op dat moment niet meer de modelleer capaciteit beschikbaar om de benodigde aanpassingen in de realisatiefase van de BRO door te voeren. We zullen dit issue na de realisatie fase alsnog oppakken.

**Comment by BregjeBrugman** [comment]
1. Herhaling van informatie: beantwoord in publieke consulatie (geen actie)
2. Bodemchemische gegevens zijn niet compleet; opgenomen als funnel issue (nr. 9) in overzicht openstaande punten: 20220622_Openstaande punten_overzicht_SFRenBHRP.xlsx. 
3. Gebruik O&M; opgenomen als funnel issue (nr. 11) in overzicht openstaande punten: 20220622_Openstaande punten_overzicht_SFRenBHRP.xlsx. 
Github issue wordt gesloten
