### ISSUE TITLE
tekstuele verbetering gelaagde inhomogeniteit

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/SPR#5]
# Type issue
Bevinding vanuit WENR

# Waar
catalogus 0.99 sectie 9.5.20 gelaagde inhomogeniteit -> toelichting (pag 70)

# Samenvatting
Kleine tekstuele verbetering

# Beschrijving
Toelichting
Het gegeven geeft aan of er in een laag die beschreven is als bestaand uit een soort grond, dunne laagjes voorkomen van ander, natuurlijk materiaal. De laagjes hebben een natuurlijke oorsprong en zijn samen met de laag gevormd.
Bij gegevens van Wageningen Environmental Research die uit de registratie BIS Nederland komen en aangeleverd zijn in het kader van archiefoverdracht, is de gelaagde inhomogeniteit zelden vastgelegd. ->

Toelichting
Het gegeven geeft aan of er in een laag die beschreven is als bestaand uit een soort grond, dunne laagjes voorkomen van ander, natuurlijk materiaal. De laagjes hebben een natuurlijke oorsprong en zijn samen met de laag gevormd.
Bij gegevens van Wageningen Environmental Research die uit de registratie BIS Nederland komen en aangeleverd zijn in het kader van archiefoverdracht, is de gelaagde inhomogeniteit **niet gestructureerd vastgelegd maar als opmerking omschreven**.

# Oplossingsrichting
tekst aanpassen in volgende versie catalogus

**Comment by BregjeBrugman** [comment]
verwerkt in versie 2.099 (ter vaststelling) dd 28-juli-2022 (wordt versie 2.1). 
Gegeven alleen van toepassing op  SFR
