### ISSUE TITLE
Wandonderzoek

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/SPR#50]
## Type issue
Publieke consultatie

## Van
WEnR

## Waar
Wandonderzoek

## Samenvatting
foute benaming: grond ipv bodem

## Beschrijving
in (15) wordt ‘grond’ als benaming gebruikt terwijl in de bodemkunde ‘bodem’ passender zou zijn. We spreken ook van bodemlaag en niet van grondlaag in (13). Nu wordt er in de inleiding onderscheid gemaakt in bodem, grond en gesteente met name om over meerdere domeinen heen te standaardiseren, echter hier gaat het echt om de bodem en kan een bodemlaag ook gesteente bevatten of zijn.

## Oplossingsrichting
Voorstel wijzig 'grond' in ‘bodem’

**Comment by BregjeBrugman** [comment]
Zie antwoord terugkoppeling publieke consultatie: 

Het betreffende maakt deel uit van de standaard welke reeds in tranche 2 is vastgesteld. De motivatie uit tranche 2 was als volgt:  
Met grond wordt hier bedoeld het materiaal waaruit de laag bestaat. In de BRO is de benaming generiek. Het is onafhankelijk of het hier gaat over een bodem- of grondlaag.  
Doel van deze consultatie was nieuw toegevoegde functionaliteit. In de beheerfase kunnen we hier nogmaals naar kijken mogelijk in de bredere context van een harmonisatie over vakgebieden heen.

**Comment by BregjeBrugman** [comment]
Issue is opgenomen in de funnel van de keten; https://jira.gdnnet.nl/browse/BROF-102
