### ISSUE TITLE
Onduidelijkheid op pagina 128

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#52]
## Type issue
Publieke consultatie 

## Waar
Pagina 128## Samenvatting
[Korte tekst van de melding. Bijvoorbeeld: 'De tekst is hier onduidelijk.']

## Beschrijving
Bij rapportsgrens staat aangegeven 'mogelijk geen waarde' Ja en een 'reden geen waarde'. Bij organischestof gehalte staat wel aangegeven 'reden geen waarde' maar geen attribuut 'mogelijk geen waarde'. Op basis van het aanwezig zijn van 'reden geen waarde' neem ik aan dat 'mogelijk geen waarde' ook Ja is hier.

## Oplossingsrichting
Mogelijk geen waarde toevoegen aan orgnischestofgehalte op P 128.

**Comment by BregjeBrugman** [comment]
Aangepast in catalogus v1.99
