### ISSUE TITLE
Probleem met angularity bij aggregaten

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#53]
## Type issue
Aanlevering

## Samenvatting
In BIS leiden we aggregate informatie af van sturtuurtype (S_TYpe). Voor pl_S_TYPE = 'rpe' geldt volgens onze interne (BIS) regels dat je geen Angularity aangeeft. Dit betekent dat in de catalogus de regel bij hoekigheid (Angularity) moet worden aangepast van "Het gegeven is aanwezig..." naar "Het gegeven mag aanwezig zijn..."

## Beschrijving
Catalogus is te streng.

## Oplossingsrichting
In de catalogus de regel bij hoekigheid (Angularity) moet worden aangepast van "Het gegeven is aanwezig..." naar "Het gegeven mag aanwezig zijn..."

**Comment by OnnoRoosenschoon** [comment]
Voorgestelde oplossing iets anders verwoord: voor kwaliteitsregime IMBRO/A zou de regel dat het verplicht aanwezig moet zijn, niet moeten gelden.

**Comment by BregjeBrugman** [comment]
waarde onbekend op genomen in werkafspraak tranche 3
