### ISSUE TITLE
Ontbreken waarde 'stoofdroog J/N' in krimptoestand SFR-P noch BHR-P. 

### ISSUE THREAD

**Issue by VianaAchthoven** [BROprogramma/SPR#54]
**Verzoekwijziging**  Review sessie en Publieke consultatie

Onderwerp
Bij het testen van nieuwe datamodel voor de bodemfysische gegevens in BIS om data voor krimp in te laden, bleek dat een waarde voor krimp, m.n. stoofdroog J/N, niet is meegenomen in in krimptoestand SFR-P noch BHR-P. 

Beschrijving
Voor een krimptoestand dienen de volgende 5 waarden (sommige optioneel) beschikbaar te zijn
- diameter
- hoogte
- volume
- masss (klopt de spelling?)
- stoofdroog J/N
De laatste waarde (stoofdroog J/N) ontbreekt en is van belang. Om onduidelijke reden is deze niet opgemerkt tijdens de reviews.  

Oplossingsrichting
Data analist na overleg met stakeholders vanwege het zwaarwegend belang om na te gaan hoe de ontbrekende waarde (stoofdroog J/N) alsnog toe te voegen aan het datamodel voor de bodemfysische gegevens in BIS.

Contactpersonen: Janneke de Heij (Data analist TNO), Yke van Randen en Gerben Bakker (Environmental Sciences Group, Wageningen University & Research)

**Comment by yke** [comment]
Uit overleg met Gerben Bakker kwam naar voren dat krimp data zonder stoofdroog niet bruikbaar is. Deze kolom is absoluut noodzakelijk.

**Comment by BregjeBrugman** [comment]
Dit wordt methodisch opgevangen. De laatste meting in de meetreeks is altijd stoofdroog. Geen aanpassing nodig.

**Comment by OnnoRoosenschoon** [comment]
Dit is niet voldoende. Dan moet je dus altijd de catalogus raadplegen om je dit te realiseren. We herhalen: Deze kolom is absoluut noodzakelijk.

**Comment by fterpstra** [comment]
De huidige oplossing is op de manier de Bregje aangeeft afgesproken met Gerben Bakker. Onno checked nogmaals met Gerben.
