### ISSUE TITLE
aantLD1 vs aantaID1

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#55]
## Type issue
Publieke consultatie

## Waar
Op pagina 112 par 3.43.2 staat bij methode aanta**l**D1 echter in de tabel 1.5 pagina 157 staat aanta**I**D1.
(Ene keer met lowercase L andere keer met kapitaal I)
## Oplossingsrichting
Maak ze gelijk (ik weet niet welke waarde goed is). Gerben Bakker van WENR kan eventueel toelichten.

**Comment by BregjeBrugman** [comment]
Schrijffout in waarde in waardelijst (niet in overeenstemming met verwijzing in regels). Moet zijn: kleine letter l (ipv hoofdletter i)

**Comment by BregjeBrugman** [comment]
Moet zijn _aantalD1_ en _aantalD2_ (met kleine letter L). Waarden in waardelijst zijn aangepast in werkafspraak stap 1
