### ISSUE TITLE
BIj krimpbepaling ontbreekt procedure schuifmaat

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#56]
## Type issue
Publieke consultatie

## Waar
Paragraaf 3.43.2 pagina 112

## Samenvatting
Procedure schuifmaat ontbreekt, is bij WENR de meest gebruikte.

## Oplossingsrichting
Toevoegen, Gerben Bakker van WENR kan toelichten.

**Comment by BregjeBrugman** [comment]
waarde geen (schuifmaat, oftewel aantalD1 en aantalD2 wordt uitgevoerd zonder procedure) opgenomen in werkafspraak tranche 3 (nr. 25)
