### ISSUE TITLE
Fout in conceptuele model, onderzocht interval en bepalingen foute cardinaliteit

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#57]
## Type issue
Review sessie

## Waar
Catalogus pagina 11

## Samenvatting
In het model (https://basisregistratieondergrond.nl/publish/library/265/20190507_catalogus_bodemkundig_wandonderzoek_1) staat dat een onderzocht interval 0 of 1 korrelgrootteverdeling heeft. WENR heeft profielkuilen waar meerdere monsters in de zelfde profielkuil op zelfde diepte genomen zijn (duplos) en die elk een eigen korrelgroottverdeling hebben. Bij het aanleveren aan BRO was het uitgangpunt van WENR om unieke intervallen te leveren (qua diepte). Dit omdat vanuit BRO aangegeven is dat dubbele intervallen (dus 2 intervallen met zelfde diepte), onwenselijk was.

Echter gezien omdat WENR ook bij deze dubbele monsters beide korrelgrootteverdelingen wil leveren zien we geen andere mogelijkheid dan voor beide monsters een interval af te leiden. De door WENR geleverde intervallen zullen dus qua dieptes identiek zijn.

Overigens geldt dit ook voor
* Bepaling zuurgraad
* Bepaling organische stof
* Bepaling organische koolstof

## Oplossingsrichting
* WENR kan met huidig model wel uit de voeten alleen door sommige intervallen dubbel te leveren. Is misschien wel wat vreemd voor datagebruikers die dubbele intervallen zien met mogelijk iets andere resultaten (kan door lokale variatie) zonder toelichting.
* Pas het TO (levert XSD's) aan zodat de cardinaliteit van bovenstaande associaties gewijzigd wordt in 0..n.

De laatste oplossing heeft de voorkeur van WENR.

**Comment by BregjeBrugman** [comment]
wordt opgelost in een volgende versie van de catalogus. Voor nu workaround (dubbel interval registreren) voor bepaling organische stof.
org. koolstofgehalte en zuurgraad vallen onder de chemische bepalingen en zijn buiten scope.

**Comment by BregjeBrugman** [comment]
opgenomen als funnel issue (nr. 23) in overzicht openstaande punten: 20220622_Openstaande punten_overzicht_SFRenBHRP.xlsx.
Github issue wordt gesloten
