### ISSUE TITLE
Inconsistentie in codelijst bepalingsmethode krimpbepaling

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#58]
## Type issue
Review sessie 

## Waar
Pagina 112,157

OP pagina 112 staat als mogelijke waarde voor de bepalingsmethode aantalD1 echter in de codelijst staat aantaID1.

Het probleem is dat aantal op pagina 112 geschreven is met lowercase L maar op pagina 157 met uppercase I. Deze twee matchen dus iet.

## Oplossingsrichting
Pas 1 van beide aan, overigens geldt dit ook voor aantalD2

**Comment by BregjeBrugman** [comment]
is gelijk aan #55
