### ISSUE TITLE
attribuut bodemvochtpotentiaal van meetreeks waterretentiewaarde  geen format

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#59]
## Type issue
.Review sessie .

## Waar
Op pagina 130 van de catalogus staat het attribuut bodemvochtpotentiaal van meetreeks waterretentiewaarde beschreven. Als domein staat daar 

Meetwaarde.

Bij alle andere numerieke attributen is extra informatie toegevoegd over ‘format’. Bv bij volumetrisch watergehalte (volgende attribuut) staat Meetwaarde 1.3, net als bij massa watergehalte.

## Oplossingsrichting
Volgens Janneke de Heij moet het meetwaarde 8.0.

![image](https://user-images.githubusercontent.com/5520961/90150030-77e35f00-dd85-11ea-9407-557eeb9fabb0.png)

**Comment by yke** [comment]
Opmerking van Gerben okt 2020 moet zijn 8.1

**Comment by BregjeBrugman** [comment]
vervangen door #70
