### ISSUE TITLE
tekstuele aanpassing brokje

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/SPR#6]
## Type issue
Bevinding vanuit WENR

## Waar
catalogus 0.99 sectie 9.5.21 brokje -> toelichting (pag 71)

## Samenvatting
Kleine tekstuele verbetering 

## Beschrijving
Toelichting
Het gegeven geeft aan of er in een laag die beschreven is als bestaand uit grond, brokjes voorkomen die afwijken van de grondsoort. Het gegeven geeft niet wat de herkomst is van het materiaal. De brokjes kunnen als deel van de grond zijn afgezet maar ook door vermenging in de grond zijn terechtgekomen. Alleen in het geval de laag gemengd is (gemengd heeft de waarde ja), kan de herkomst aan menselijk handelen worden toegeschreven. Bij gegevens van Wageningen Environmental Research die uit de registratie BIS Nederland komen en aangeleverd zijn in het kader van archiefoverdracht, is dit gegeven zelden vastgelegd. ->

Toelichting
Het gegeven geeft aan of er in een laag die beschreven is als bestaand uit grond, brokjes voorkomen die afwijken van de grondsoort. Het gegeven geeft niet wat de herkomst is van het materiaal. De brokjes kunnen als deel van de grond zijn afgezet maar ook door vermenging in de grond zijn terechtgekomen. Alleen in het geval de laag gemengd is (gemengd heeft de waarde ja), kan de herkomst aan menselijk handelen worden toegeschreven. Bij gegevens van Wageningen Environmental Research die uit de registratie BIS Nederland komen en aangeleverd zijn in het kader van archiefoverdracht, is dit gegeven **niet gestructureerd vastgelegd maar als opmerking omschreven.**

## Oplossingsrichting
tekst aanpassen in volgende versie catalogus

**Comment by BregjeBrugman** [comment]
verwerkt in versie 2.099 (ter vaststelling) dd 28-juli-2022 (wordt versie 2.1).
Gegeven alleen van toepassing op SFR
