### ISSUE TITLE
Uitbreiding codelijst BijzonderheidMateriaal

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#63]
## Type issue
Review sessie 
Bij bijzonderheid materiaal is de waarde 'geen' niet toegestaan, Mijn collega Gerben Bakker wil deze graag wel erbij hebben.

## Waar
Tabel 1.12 pagina 170

## Samenvatting
Nu

![image](https://user-images.githubusercontent.com/5520961/95433781-ba25b880-0950-11eb-8b1f-06f04f87aa8d.png)

## Beschrijving
Is consistenter over codelijsten en is duidelijker. Als je geen invult weet je dat je het niet vergeten bent. 

Neem even contact op met Gerben.bakker@wur.nl

**Comment by BregjeBrugman** [comment]
waarde _geen_ is toegevoegd in de werkafspraak tranche 3 (nr.14). De kardinaliteit van de betreffende gegevens wordt aangepast in een volgende versie.

**Comment by BregjeBrugman** [comment]
Het aanpassen van de kardinaliteit is opgenomen als uitgewerkt issue (nr. 4 en 5) in overzicht openstaande punten: 20220622_Openstaande punten_overzicht_SFRenBHRP.xlsx.
Github issue wordt gesloten
