### ISSUE TITLE
Uitbreiding codelijst BijzonderheidUitvoering

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#64]
## Type issue
Review sessie 

## Waar
Tabel 1.13 Pagina 170

## Samenvatting
Gerben Bakker wil ook hier graag de waarde 'geen' toevoegen

Neem even contact op met Gerben.bakker@wur.nl

## Beschrijving
Is consistenter over codelijsten en is duidelijker. Als je geen invult weet je dat je het niet vergeten bent.

**Comment by BregjeBrugman** [comment]
waarde _geen_ is toegevoegd in de werkafspraak tranche 3 (nr.34). De kardinaliteit van de betreffende gegevens wordt aangepast in een volgende versie.

**Comment by RuudMutsaers** [comment]
Is opgelost in nieuwe versie
