### ISSUE TITLE
catalogi V0.99 en V1.99: tegenstrijdige regels op gemiddeld laagste grondwaterstand

### ISSUE THREAD

**Issue by weeginkjw** [BROprogramma/SPR#65]
Bevinding BRO-LV team bij de vergelijking van de business rules in de catalogi versies 0.99 en 1.99

tegenstrijdige regels op  _**gemiddeld laagste grondwaterstand**_
de regel in V 1.99 klopt niet

Catalogus V 0.99: Het gegeven mag aanwezig zijn wanneer het attribuut gemiddeld hoogste grondwaterstand aanwezig is. In andere gevallen ontbreekt het gegeven. De waarde mag niet kleiner zijn dan de waarde van de gemiddeld hoogste grondwaterstand. De waarde mag niet groter zijn dan de einddiepte wand van de entiteit Wandontsluiting.	

Catalogus V 1.99: Het attribuut mag **niet** aanwezig zijn wanneer het attribuut gemiddeld hoogste grondwaterstand aanwezig is. De waarde mag niet kleiner zijn dan de waarde van de gemiddeld hoogste grondwaterstand. De waarde mag niet groter zijn dan de einddiepte wand van de entiteit Wandontsluiting.

Oplossingsrichting: aanpassing business rule in catalogus V1.99 naar: _"Het attribuut mag niet aanwezig zijn wanneer het attribuut gemiddeld hoogste grondwaterstand niet aanwezig is."_ 
(dat betekent dat het aanwezig mag zijn wanneer het attribuut gemiddeld hoogste grondwaterstand aanwezig is)

**Comment by BregjeBrugman** [comment]
Regel aangepast in werkafspraak tranche 3 (nr.5).
