### ISSUE TITLE
Waterretentieverdamping BodemVochtPotentiaalOpDiepte1..4 

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#67]
## Type issue
Review sessie 

## Waar
Pagina 141

## Samenvatting
[Korte tekst van de melding. Bijvoorbeeld: 'De tekst is hier onduidelijk.']

## Beschrijving
Alls BodemVochtPotentiaal Diepte1..4 kolommen moeten format 8.1 krijgen.

## Oplossingsrichting
Aanpassen, neem even contact op met Gerben Bakker WENR.

**Comment by BregjeBrugman** [comment]
vervangen door #70
