### ISSUE TITLE
Watergehalte en doorlatendheid bij bepaalde bodemvochtpotentiaal =>bodemvochtpotentiaal 

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#68]
## Type issue
Publieke consultatie/Review sessie [verwijderen wat niet van toepassing is]

## Waar
Pagina 3.57.1 bodemvochtpotentiaal

## Samenvatting
Formaat moet worden 8.1 ipv 8.0

## Beschrijving
Neem even contact op met Gerben Bakker.

## Oplossingsrichting
[Geef een suggestie voor een oplossing, in de vorm van een tekstvoorstel of een oplossingsrichting.]

**Comment by BregjeBrugman** [comment]
vervangen door #70
