### ISSUE TITLE
Waterdoorlatenheid => bodemvochtpotentiaal

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#69]
## Type issue
Review sessie 

## Waar
3.48.1 bodemvochtpotentiaal

## Samenvatting
Formaat 8.0 moet 8.1 worden

## Beschrijving
neem even contact ip Gerben Bakker WENR

 ## Oplossingsrichting
Aanpassen

**Comment by BregjeBrugman** [comment]
vervangen door #70
