### ISSUE TITLE
tekstuele aanpassing OrganischstofgehalteklasseNEN5104

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/SPR#7]
## Type issue
Bevinding vanuit WENR

## Waar
catalogus 0.99 sectie 51 organischstofgehalteklasse -> omschrijving zwakhumeus, matighumeus, sterkhumeus(pag 16,1632)

## Samenvatting
Kleine tekstuele verbetering 

## Beschrijving
Voor alle drie deomschrijvingen "de grond als een klei benoemd is" vervangen door: **tenzij de waarde van het attribuut bodemkundige grondsoort gelijk is aan zeerLichteZavel, matigLichteZavel, zwareZavel, lichteKlei, matigZwareKlei, zeerZwareKlei, SiltigeLeem of zandigeLeem is,** 

## Oplossingsrichting
tekst aanpassen in volgende versie catalogus

**Comment by BregjeBrugman** [comment]
verwerkt in versie 2.099 (ter vaststelling) dd 28-juli-2022 (wordt versie 2.1).
Bij SFR (bij BHR-P was het al verwerkt in 2.0).
