### ISSUE TITLE
Aanpassingen in formaten voor SFR analyses (geldt ook voor BHR-P) vervangt issues 59,61,67,68,69

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#70]
## Type issue
Review sessie

## Waar
Diverse plekken in catalogus SFR / BHR-P (het SRCommon deel dus).

## Samenvatting
Zie bijgevoegde XLSX 
[Resoluties.xlsx](https://github.com/BROprogramma/SFR/files/5457263/Resoluties.xlsx)

De nrs in kolom A refereren aan de paragraaf nrs en de nrs van de entiteiten in de diverse diagramman.

Dit vervangt issues 59,61,67,68,69

## Beschrijving
In een aantal gevallen kloppen de opgegeven decimalen voor sommige attributen niet. Mijn collega Gerben Bakker is door de catalogus gegaan en heeft gecorrigeerd.

## Oplossingsrichting
Aanpassen conform gewenste formaten in XLSX.

**Comment by BregjeBrugman** [comment]
formaten voor bodempotentiaal aangepast (stap 1) #https://github.com/BROprogramma/BHR-P/issues/69
andere formaten volgen

**Comment by BregjeBrugman** [comment]
nauwkeurigheid bodemvochtpotentiaal aangepast in werkafspraak tranche 3 (nr. 40), al in stap 1
nauwkeurigheid vormfactoren aangepast in werkafspraak tranche 3 (nr. 13)
nauwkeurigheid volumetrisch watergehalte van de waterretentiekarakteristiek aangepast in werkafspraak tranche 3 (nr. 22)
nauwkeurigheid (verzadigde) waterdoorlatendheid verandert in meetwaarden in machten in werkafspraak tranche 3 (nr. 21)


verlopen tijd (attribuut van Waterretentiewaarde verdamping) is voor een volgende versie

**Comment by BregjeBrugman** [comment]
verlopen tijd (attribuut van Waterretentiewaarde verdamping) is opgenomen als uitgewerkt issue (nr. 3) in overzicht openstaande punten: 20220622_Openstaande punten_overzicht_SFRenBHRP.xlsx.
Github issue wordt gesloten
