### ISSUE TITLE
XSD: volgorde van attributen is gewijzigd 

### ISSUE THREAD

**Issue by sjaakd** [BROprogramma/SPR#71]
## Type issue
implementatie

## Waar

Verwisseling `SFR_AbstractReportType` (issfrmessages.xsd):
•	`SiteCharacteristics`
•	`SoilUncovering`

Verwisseling `LitterLayer` (sfrcommon.xsd): 
 •	`estimatedOrganicMatterContent`
•	`litterTYpe`

## Samenvatting
Niet conform afspraak.

## Oplossingsrichting
XSD aanpassen (is reeds gebeurd als input)

**Comment by HanWelmer** [comment]
- Documentatie Technisch Ontwerp Increment 2 bijgewerkt (https://wiki.gdnnet.nl/pages/viewpage.action?pageId=61342921)
- Logisch model bijgewerkt
- XSD is al bijgewerkt.
- worddoc met beschrijving brondocumenten SFR-volledigRapport wordt hierdoor niet geraakt
- worddoc met beschrijving uitgiftedocumenten SFR-O en SFR-O-DP wordt hierdoor niet geraakt
- Berichtencatalogus inname wordt hierdoor niet geraakt.
- Berichtencatalogus inname wordt hierdoor niet geraakt.
