### ISSUE TITLE
SFR Catalogus: 3.32.5 dispersiemethode

### ISSUE THREAD

**Issue by weeginkjw** [BROprogramma/SPR#72]
bevinding BRO-LV

SFR catalogus

3.32.5    dispersiemethode
Type gegeven   Attribuut van Bepaling korrelgrootteverdeling
Kardinaliteit      1
Regels  **Het attribuut mag niet aanwezig zijn** wanneer de waarde van het attribuut bepalingsmethode gelijk is aan natDroogZeven.
Het attribuut moet aanwezig zijn in alle andere gevallen. 

Is dit een foute kardinaliteit?

**Comment by weeginkjw** [comment]
****

**Comment by weeginkjw** [comment]
BRO-LV team past de xsd aan

**Comment by weeginkjw** [comment]
[SFR_issues_72.pdf](https://github.com/BROprogramma/SFR/files/5595855/SFR_issues_72.pdf)

**Comment by sjaakd** [comment]
de XSD is inmiddels aangepast

**Comment by BregjeBrugman** [comment]
De regel moet vervallen (sorry) :-(

**Comment by BregjeBrugman** [comment]
regel vervallen is opgenomen in werkafspraak tranche 3 (nr. 36), al in stap 1 verwerkt
