### ISSUE TITLE
characteristicsModelled moet zijn characteristicModelled

### ISSUE THREAD

**Issue by sjaakd** [BROprogramma/SPR#74]
## Type issue
implementatie

## Waar
XSD

## Samenvatting
Altijd fijn als jullie even de aandacht vragen voor een Engelse tem. Want ja die worden bepaald door het werkveld en door ons vastgelegd, maar dat betekent niet dat het foutloos is 😊.

Het attribuut karakteristiek gemodelleerd (van de entiteit Onderzocht interval) is in het conceptueel model vertaald als characteristicModelled (bij zowel SFR als BHR-P). Dat is het gegeven bedoeld is in de kenmerkenverzameling (CriteriaSet) en het is ook bedoeld dat we dan dezelfde term hanteren. 

Ik zie dat in de beschrijving van de kengegevens (worddoc) ook de Engelse vertalingen zijn opgenomen en daar staat characteristicsModelled, en dat is de input voor Han voor uitgifte. Daar staat het dus fout. Ik zal de beschrijving van de kengegevens aanpassen en voor gegevens die zijn opgenomen in de catalogus verwijzen naar het conceptueel model voor de engelse termen zodat we ze niet op 2 plekken registreren.

## Oplossingsrichting
pas XSD aan

**Comment by HanWelmer** [comment]
- worddoc met beschrijving uitgiftedocumenten bijgewerkt. (zie versie 20211026 op pagina https://wiki.gdnnet.nl/display/BSta/Brondocumenten+en+uitgifte+documenten+SFR)
- Logisch model is al bijgewerkt.
- XSD is al bijgewerkt.
- Berichtencatalogus inname wordt hierdoor niet geraakt.
- Berichtencatalogus uitgifte is al bijgewerkt.
