### ISSUE TITLE
opbouw Bepalingscode (attribuut bepalingsID - SFR en BHR-P) voor Modellering van hydrofysische karakteristieken

### ISSUE THREAD

**Issue by weeginkjw** [BROprogramma/SPR#75]
Bevinding BRO-LV team

Catalogus BHR-P: 3.59.1	Modellering van hydrofysische karakteristieken.bepalingsID
Catalogus SFR: 3.58.1	Modellering van hydrofysische karakteristieken,bepalingsID

De toelichting van het attribuut bepalingsID bij Modellering van hydrofysische karakteristieken is analoog aan die van 3 andere attributen bepalingsID (bij Bepaling waterdoorlatendheid, Bepaling waterretentie stapsgewijs en Bepaling watergehalte en doorlatendheid bij veranderende bodemvochtpotentiaal): _". . . De opbouw van het gegeven bestaat uit drie letters voor de naam van de bepaling (CCC) en een volgnummer dat uit 2 cijfers (NN) bestaat."_

Na overleg met Yke van Randen (WENR) blijkt dat bij dit attribuut de CCC niet een vaste prefix is (zoals bij de 3 andere attributen wel het geval is) maar een prefix van 3 willekeurige letters. In de BRO is dit actueel als 3 willekeurige letters geimplementeerd (UPPER of lower case).

Oplossingsrichting: aanpassing in de Catalogi van de toelichting van bepalingsID voor Modellering van hydrofysische karakteristieken naar een formulering in de trant van: _". . . De opbouw van het gegeven bestaat uit drie wilekeurige (hoofd)letters voor de naam van de bepaling (CCC) en een volgnummer dat uit 2 cijfers (NN) bestaat."_
Vraag is nog of het (zoals Yke voorstelt) alleen UPPER case moet zijn.

**Comment by BregjeBrugman** [comment]
opgenomen als uitgewerkt issue (nr. 6) in overzicht openstaande punten: 20220622_Openstaande punten_overzicht_SFRenBHRP.xlsx.
Github issue wordt gesloten
