### ISSUE TITLE
Problemen met soort analyse in wandmonsteranalyse entiteit

### ISSUE THREAD

**Issue by yke** [BROprogramma/SPR#77]
## Type issue
Review sessie

## Samenvatting
Soort analyse is opgenomen bij wandmonsteanalyse entiteit (ook bij BHR-P boormonsteranalyse) en wordt eenmalig gevuld. Op basis van deze ene waarde wordt bij de intervallen bepaald welke bepalingen aanwezig kunnen zijn, moeten zijn en niet mogen zijn.

Probleem is dat welke bepalingen gedaan zijn vaak afhangt van vraag opdrachtgever en/of soort grond. 
 
## Oplossingsrichting
Mogelijke oplossing is de regels ietwat te versoepelen. Door de regels dat een bepaalde bepaling niet toegestaan is bij een bepaalde soort analyses te droppen of te wijzigen in optioneel kan alles bijna zelfde blijven. Select bij uitgifte op soort analyses garandeert nog steeds zelfde resultaat (je kunt iets extra krijgen).

**Workaround bij WENR**

Via aanwezige bepalingen leiden we een soort analyse af. Alleen doordat in de catalogus bij sommige soort analyses is aangegeven dat sommige bepaling NIET toegestaan zijn komen wij in de problemen. Als deze regel versoepelt wordt van NIET TOEGESTAAN naar MAG AANWEZIG Zzijn (optioneel dus) dan werkt onze workaround. Gebeurt dit niet dan kunnen wij van veel profielen de analyses niet leveren.

**Comment by BregjeBrugman** [comment]
regels zijn voor IMBRO/A versoepeld in werkafspraak tranche 3 (nr. 23)
