### ISSUE TITLE
tekstuele aanpassing sterkhumeus 

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/SPR#8]
## Type issue
Bevinding vanuit WENR

## Waar
catalogus 0.99 sectie 51 organischstofgehalteklasse -> omschrijving sterkhumeus (pag 163)

## Samenvatting
Verbetering 

## Beschrijving
kan het aandeel tot 30 procent bedragen -> kan het aandeel tot **25** procent bedragen

## Oplossingsrichting
impact bepalen, ofwel tekst aanpassen in volgende versie catalogus indien de impact het rechtvaardigd werkafspraak

**Comment by BregjeBrugman** [comment]
besproken op 8-mrt-2022

**Comment by BregjeBrugman** [comment]
In versie 1. 0 (bhrp) was de grenswaarde 15 %, dat is vanaf 2.0 opgerekt naar 30 %.

**Comment by BregjeBrugman** [comment]
opgenomen op backlog: https://jira.gdnnet.nl/browse/BROSVO-1233

**Comment by BregjeBrugman** [comment]
30% is goed (getoetst bij Fokke Brouwer)
