### ISSUE TITLE
tekstuele aanpassing Inleiding paragraaf ontsluiten

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/SPR#9]
## Type issue
Bevinding vanuit WENR

## Waar
catalogus 0.99 sectie 1.2 ontsluiten (pag 183)

## Samenvatting
Kleine tekstuele verbetering 

## Beschrijving
In de bodemkundige praktijk zijn dat altijd geroerde monsters, monsters .... ->
In de bodemkundige praktijk zijn dat  **veelal** geroerde monsters **(uitzondering van een gutsboring)**, monsters ....

## Oplossingsrichting
tekst aanpassen in volgende versie catalogus

**Comment by BregjeBrugman** [comment]
Niet aangepast in versie 2.099 (ter vaststelling) dd 28-juli-2022 (wordt versie 2.1).
Gegeven alleen van toepassing op SFR

**Comment by BregjeBrugman** [comment]
issue op redactionele lijst opgenomen en hier gesloten
